name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: |
        cd backend
        npm ci
        cd ../frontend
        npm ci
    - name: Run ESLint
      run: |
        cd backend
        npm run lint
        cd ../frontend
        npm run lint
    - name: Check Prettier formatting
      run: |
        cd backend
        npm run format:check
        cd ../frontend
        npm run format:check

  build:
    runs-on: ubuntu-latest
    needs: lint-and-format
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies and build
      run: |
        cd backend
        npm ci
        npm run build
        cd ../frontend
        npm ci
        npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies and run tests
      run: |
        cd backend
        npm ci
        npm test
        cd ../frontend
        npm ci
        npm test
